### ISSUE TITLE
Unaligned margins

### ISSUE THREAD

**Issue by PhilipBale** [hyperoslo/Form#444] opened 2015-08-26 04:37 UTC
Hi,

Seems to give: http://puu.sh/jOQKV/8cc7766f9b.png by default, using 100, 100, 50/50, 33/33/33 widths.  Should this be the behavior?

**Comment by 3lvis** [comment] 2015-08-26 04:46
Hi Philip,

This doesn't seem right, would you mind providing an example of your JSON file so I can reproduce the issue? 

:)

**Comment by PhilipBale** [comment] 2015-08-26 13:11
Sure!  Here it is 
{
   "groups":[
     {
      "id":"group-id",
      "title":"Group title",
      "sections":[
         {
            "id":"section-0",
            "fields":[
               {
                  "id":"title",
                  "title":"Title*",
                  "type":"text",
                  "size":{
                     "width":100
                  }
               },
               {
                  "id":"location",
                  "title":"Location*",
                  "type":"text",
                  "size":{
                     "width":100
                  }
               },
               {
                  "id":"date",
                  "title":"Date*",
                  "type":"date",
                  "size":{
                     "width":50
                  }
               },
               {
                  "id":"attire",
                  "title":"Attire*",
                  "type":"select",
                  "size":{
                     "width":50
                  },
                  "values":[
                     {
                        "id":0,
                        "title":"Casual",
                        "default":true
                     },
                     {
                        "id":1,
                        "title":"Formal"
                     }
                  ]
               },
               {
                  "id":"size",
                  "title":"Size*",
                  "type":"text",
                  "size":{
                     "width":33
                  }
               },
               {
                  "id":"min_age",
                  "title":"Min age",
                  "type":"number",
                  "size":{
                     "width":33
                  }
               },
               {
                  "id":"max_age",
                  "title":"Max age",
                  "type":"number",
                  "size":{
                     "width":33
                  }
               }
            ]
         }
      ]
   }
  ]
}

**Comment by jeffleeismyhero** [comment] 2015-08-26 13:22
When using the provided JSON below in the latest commit of Form, I get the following form:

![screenshot 2015-08-26 08 18 33](https://cloud.githubusercontent.com/assets/43980/9494442/77056782-4bcb-11e5-9b6d-07d4c0061219.png)

What version of Form are you using?

**Provided JSON**
```json
{  
    "groups":[  
        {  
            "id":"group-id",
            "title":"Group title",
            "sections":[  
                {  
                    "id":"section-0",
                    "fields":[  
                        {  
                            "id":"title",
                            "title":"Title",
                            "type":"text",
                            "size":{  
                                "width":100
                            }
                        },
                        {  
                            "id":"location",
                            "title":"Location",
                            "type":"text",
                            "size":{  
                                "width":100
                            }
                        },
                        {  
                            "id":"date",
                            "title":"Date",
                            "type":"date",
                            "size":{  
                                "width":50
                            }
                        },
                        {  
                            "id":"attire",
                            "title":"Attire",
                            "type":"select",
                            "size":{  
                                "width":50
                            },
                            "values":[  
                                {  
                                    "id":0,
                                    "title":"Casual",
                                    "default":true
                                },
                                {  
                                    "id":1,
                                    "title":"Formal"
                                }
                            ]
                        },
                        {  
                            "id":"size",
                            "title":"Size*",
                            "type":"text",
                            "size":{  
                                "width":33
                            }
                        },
                        {  
                            "id":"min_age",
                            "title":"Min age",
                            "type":"number",
                            "size":{  
                                "width":33
                            }
                        },
                        {  
                            "id":"max_age",
                            "title":"Max age",
                            "type":"number",
                            "size":{  
                                "width":33
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by PhilipBale** [comment] 2015-08-26 13:25
I was using the most recent on an iPhone in portrait.

**Comment by jeffleeismyhero** [comment] 2015-08-26 13:37
Could you provide exact specs for the environment?

This is what I see in the iPhone 6 / iOS 8.4 simulator with your JSON:

![ios simulator screen shot aug 26 2015 8 32 21 am](https://cloud.githubusercontent.com/assets/43980/9494711/1c16a398-4bcd-11e5-8e49-cd0ad99becfd.png)

iPhone 4s simulator:

![ios simulator screen shot aug 26 2015 8 33 55 am](https://cloud.githubusercontent.com/assets/43980/9494725/3e17b310-4bcd-11e5-887a-03e21cc728a9.png)

**Comment by PhilipBale** [comment] 2015-08-26 14:05
That's what I'm going for :p 

Here is the gist of the FormViewController: https://gist.github.com/PhilipBale/dc5840fc1c96bceba588

I'm using a CollectionViewController in my storyboard.

**Comment by richardoti** [comment] 2015-08-27 12:17
@PhilipBale don't you mind if I take your JSOn to use as iPhone FORM example? I may try to test your case.

**Comment by richardoti** [comment] 2015-08-27 13:08
@PhilipBale I've found the way how to fix your bug.
The problem is that when storyboards are being used, the initializer:
```Objective-C
- (instancetype)initWithJSON:(id)JSON
            andInitialValues:(NSDictionary *)initialValues
                    disabled:(BOOL)disabled {

```
is not being called. `initWithCoder` is being called as the default, so the `UICollectionViewController` is being initialized with default flow layout. Not the `FORMLayout` which is needed. Later, in your implementation you set up the proper Layout to the datasource, but  you do not set it to the collection view itself. Collection view is still using default flow layout. To fix, just copy this code:
```Objective-C
- (FORMDataSource *)dataSource {
    if (_sourceData) return _sourceData;

    FORMLayout *layout = [FORMLayout new];

    NSArray *JSON = [NSJSONSerialization JSONObjectWithContentsOfFile:@"CreateEvent.json"];
    _sourceData = [[FORMDataSource alloc] initWithJSON: JSON
                                        collectionView:self.collectionView
                                                layout:layout
                                                values:nil
                                              disabled:NO];

    self.collectionView.collectionViewLayout = layout;
    __weak typeof(self)weakSelf = self;

    _sourceData.configureCellBlock = ^(FORMBaseFieldCell *cell, NSIndexPath *indexPath, FORMField *field) {
        cell.field = field;

    };

    _sourceData.fieldUpdatedBlock = ^(FORMBaseFieldCell *cell, FORMField *field) {

    };

    return _sourceData;
}
```
![ios simulator screen shot 27 aug 2015 15 08 09](https://cloud.githubusercontent.com/assets/8013017/9521177/842d43a0-4ccd-11e5-9ce3-c94da62f03f2.png)

**Comment by PhilipBale** [comment] 2015-08-27 14:15
Thank you very much!!

**Comment by richardoti** [comment] 2015-08-27 15:09
@PhilipBale :smile:
I think, we can close this issue, but, overall, Form integration with storyboards may be improved.
I.e. it would be good to have option for setting layout directly in storyboard without specifying it in code.

**Closed by richardoti** 2015-08-27 15:09 UTC

**Comment by 3lvis** [comment] 2015-08-27 18:35
@richardoti could you make an issue for suggestions on how to improve using Form with storyboards, please :grin: ?

**Comment by richardoti** [comment] 2015-08-27 20:14
@3lvis why not :+1:
